name: Mobile

on:
  push:
    branches:
      - "githubactions"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_Mobile:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v2   
              
      - name: Install Boots 
        run: |
          dotnet tool install --global boots
          boots https://aka.ms/xamarin-android-commercial-d16-9-macos
          boots https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.122.macos10.xamarin.universal.pkg

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build Android App
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./BloodPressureTracker/BloodPressureTracker.Android/BloodPressureTracker.Android.csproj /verbosity:normal /p:Configuration=Debug     
          
      - name: Build iOS App
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./BloodPressureTracker/BloodPressureTracker.iOS/BloodPressureTracker.iOS.csproj /verbosity:normal /p:Configuration=Debug /p:Platform=iPhoneSimulator
